#!/usr/bin/env bash
# displays information about specified domain and/or subdomains

print_dns_info () {
	script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -n 2 | tr '\n' ' ')
	echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" -eq 1 ]
then
	print_dns_info "$1" "www"
	print_dns_info "$1" "lb-01"
	print_dns_info "$1" "web-01"
	print_dns_info "$1" "web-02"
elif [ "$#" -eq 2 ]
then
	print_dns_info "$1" "$2"
fi
