#!/usr/bin/env bash
# Changes the IP address that localhost resolves to

# Copy contents of hosts file to new file
cp /etc/hosts ~/hosts.new

# Replace 127.0.0.1 with 127.0.0.2
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new

# Insert 8.8.8.8 facebook.com at line 2
sed -i '2i8.8.8.8 	facebook.com' ~/hosts.new

# Copy new contents back to hosts file
cp -f ~/hosts.new /etc/hosts
